# **Array Manipulation**

# chaning shape

In [ ]:
import numpy as np

In [ ]:
a = np.arange(8)
print('the original array: ')
print(a)
b = a.reshape(2,4)
print('the modified array: ')
print(b)

the original array: 
[0 1 2 3 4 5 6 7]
the modified array: 
[[0 1 2 3]
 [4 5 6 7]]


In [ ]:
print(b.flatten())

[0 1 2 3 4 5 6 7]


In [ ]:
b.flatten(order="F")

array([0, 4, 1, 5, 2, 6, 3, 7])

In [ ]:
a = np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
print(np.transpose(a))

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [ ]:
b = np.arange(8).reshape(2,4)
print(b)

[[0 1 2 3]
 [4 5 6 7]]


In [ ]:
c = b.reshape(2,2,2)

In [ ]:
np.rollaxis(c,1,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
np.swapaxes(c,1,2)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

## **Arithmetic Operations**

In [ ]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
b = np.array([10,10,10])
print(b)

[10 10 10]


In [ ]:
print(np.add(a,b))

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
print(np.subtract(a,b))

[[-10  -9  -8]
 [ -7  -6  -5]
 [ -4  -3  -2]]


In [ ]:
print(np.multiply(a,b))

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]


In [ ]:
print(np.divide(a,b))

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


# Slicing

In [ ]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
a[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
a[:4]

array([0, 1, 2, 3])

In [ ]:
s = slice(2,9,2)
print(s)

slice(2, 9, 2)


# Inserting over array

In [ ]:
a = np.arange(0,45,5)
a = a.reshape(3,3)
a

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [ ]:
for i in np.nditer(a):
  print(i)

0
5
10
15
20
25
30
35
40


# Iternation order - 'C and F style'

In [ ]:
print(a)
for i in np.nditer(a,order="C"):
  print(i)
for j in np.nditer(a,order="F"):
  print(j)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]
0
5
10
15
20
25
30
35
40
0
15
30
5
20
35
10
25
40


# Joining arrays

In [ ]:
a = np.array([[1,2],[3,4]])
print('first array')
print(a)

b = np.array([[5,6],[7,8]])
print('second array')
print(b)

first array
[[1 2]
 [3 4]]
second array
[[5 6]
 [7 8]]


In [ ]:
print('Joining two arrays along axis 0:')
print(np.concatenate((a,b)) ) #this was along the axis 0

Joining two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
print('Joining two arrays along axis 1')
print(np.concatenate((a,b), axis=1))
#remember to keep both the arrays with the same shape i.e rows and cols

Joining two arrays along axis 1
[[1 2 5 6]
 [3 4 7 8]]


# Splitting array

In [ ]:
a = np.arange(9)
print(a)
np.split(a,3)

[0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [ ]:
np.split(a,[4,7])#the first split is going to be at 4 and the next split is going to be at 7

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [ ]:
np.split(a,[4,5])#the first split is going to be at 4 and the next split is going to be at 5

[array([0, 1, 2, 3]), array([4]), array([5, 6, 7, 8])]

# Resizing the array

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
b = np.resize(a,(3,3))
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]
 [1 2 3]]
(3, 3)
